services:
  db:
    image: mariadb:lts
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./db/data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    volumes:
      - ./mail-tmp/:/tmp

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  boilerplate-db:
